### ISSUE TITLE
How to implement a loading screen or swap root? 

### ISSUE THREAD

**Issue by lanyusan** [kanzitelli/rnn-screens#5]
I need to implement a loading screen. There is a long issue in rnn-starter about splash screen. It seems it wouldn't come for a while.

I am thinking of using the technique of swapping root. It is not very clear from doc. 

Is there a way to do so with rnn-screens without using react native navigation directly?

**Comment by kanzitelli** [comment]
hey @lanyusan! it took me a while to respond, been busy these days. I have just release `v16.0.0` of [rnn-starter](https://github.com/kanzitelli/rnn-starter) where you can take advantage of splash screen! but yeah, I've used that technique a few times. what I've also done is showing overlay with loading progress after first screen is shown. So I'm going to close the issue as splash screen is released and rnn-screens will be soon replaced with [rn-navio](https://github.com/kanzitelli/rn-navio).
